# Generated by Django 5.2.3 on 2025-06-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_remove_bookpreview_file_bookpreview_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("tx_ref", models.CharField(max_length=100, unique=True)),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready for Pickup"),
                            ("collected", "Collected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=0, max_digits=30)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecomapp.bookorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecomapp.product",
                    ),
                ),
            ],
        ),
    ]
