# Generated by Django 5.2.1 on 2025-06-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0003_bookorder_bookorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("collected", "Collected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookorderitem",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
    ]
