# Generated by Django 5.2.1 on 2025-06-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0004_alter_bookorder_status_alter_bookorderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("collected", "Collected")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
