# Generated by Django 5.2.1 on 2025-06-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0005_alter_bookorder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediacontent",
            name="file_url",
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="file",
            field=models.FileField(default="null", upload_to="media_files/"),
            preserve_default=False,
        ),
    ]
