# Generated by Django 5.2.3 on 2025-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0006_remove_mediacontent_file_url_mediacontent_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediacontent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="preacher",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="scripture",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="text_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediacontent",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media_files/"),
        ),
        migrations.AlterField(
            model_name="mediacontent",
            name="media_type",
            field=models.CharField(
                choices=[("audio", "Audio"), ("video", "Video"), ("text", "Text")],
                max_length=10,
            ),
        ),
    ]
