# Generated by Django 5.2.3 on 2025-07-08 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0008_emailsubscriber_subscribermessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MediaComment",
            new_name="SermonComment",
        ),
        migrations.RenameModel(
            old_name="MediaContent",
            new_name="SermonContent",
        ),
    ]
