# Generated by Django 5.2.1 on 2025-06-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookpreview",
            name="file",
        ),
        migrations.AddField(
            model_name="bookpreview",
            name="content",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
    ]
